Makefile, src/main/java/uk/gov/companieshouse/charges/delta/config/KafkaConfig.java, src/main/java/uk/gov/companieshouse/charges/delta/producer/ChargesDeltaProducer.java
dsnd-465 code improvement and make file change
=> dsnd-465 code improvement and make file change

pom.xml, src/main/java/uk/gov/companieshouse/charges/delta/consumer/ChargesDeltaConsumer.java
Added meaningful logs for QA testing
=> dsnd-493 receiveMainMessages method log improvement

src/main/java/uk/gov/companieshouse/charges/delta/mapper/ChargeApiMapper.java, src/main/java/uk/gov/companieshouse/charges/delta/processor/Encoder.java, src/main/resources/application.yml, src/test/java/uk/gov/companieshouse/charges/delta/config/TestConfig.java, src/test/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessorTest.java, src/test/java/uk/gov/companieshouse/charges/delta/processor/EncoderTest.java, src/test/resources/charges-delta-source-2.json, src/test/resources/internal-charges-api-expected-2.json
dsnd-498: Addressed more comments from review
=> dsnd-498: Addressed more comments from review

src/main/java/uk/gov/companieshouse/charges/delta/mapper/ChargeApiMapper.java, src/main/java/uk/gov/companieshouse/charges/delta/transformer/ChargesApiTransformer.java, src/test/java/uk/gov/companieshouse/charges/delta/transformer/ChargesApiTransformerTest.java, src/test/resources/internal-charges-api-expected-2.json
dsns-498: Updated delta at mapping
=> dsns-498: Updated delta at mapping

pom.xml
DSND-541: Update private api sdk version to 2.0.130
=> DSND-541: Update private api sdk version to 2.0.130

pom.xml
DSND-541: update private jdk version
=> DSND-541: update private jdk version

src/main/java/uk/gov/companieshouse/charges/delta/processor/Encoder.java, src/test/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessorTest.java, src/test/java/uk/gov/companieshouse/charges/delta/processor/EncoderTest.java, src/test/resources/internal-charges-api-expected-2.json, src/test/resources/internal-charges-api-expected-3.json
=> fix charge Id encoding

src/main/java/uk/gov/companieshouse/charges/delta/processor/Encoder.java, src/test/java/uk/gov/companieshouse/charges/delta/processor/EncoderTest.java
DSND-704: replace forward slash with underscore and '+' with '-' from encoded value
=> DSND-704: replace forward slash with underscore and '+' with '-' from encoded value

pom.xml
DSND-704: update private api sdk
=> DSND-704: update private api sdk

pom.xml, src/itest/java/uk/gov/companieshouse/charges/delta/consumer/ChargesDeltaConsumerITest.java, src/main/java/uk/gov/companieshouse/charges/delta/consumer/ChargesDeltaConsumer.java, src/main/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessor.java, src/test/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessorTest.java, src/test/java/uk/gov/companieshouse/charges/delta/serialization/ChsDeltaDeserializerTest.java, src/test/java/uk/gov/companieshouse/charges/delta/serialization/ChsDeltaSerializerTest.java, src/test/java/uk/gov/companieshouse/charges/delta/transformer/ChargesApiTransformerTest.java, src/test/java/uk/gov/companieshouse/charges/delta/util/TestSupport.java, src/test/resources/charges-delete-delta-source-1.json
dsnd-784:Deserialisation enhancement to handle the is_delete
updated processor to handle delete
added tests
=> dsnd-784:Deserialisation enhancement to handle the is_delete

pom.xml, src/main/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessor.java, src/main/java/uk/gov/companieshouse/charges/delta/service/ApiClientService.java, src/main/java/uk/gov/companieshouse/charges/delta/service/ApiClientServiceImpl.java, src/test/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessorTest.java, src/test/java/uk/gov/companieshouse/charges/delta/service/ApiClientServiceImplTest.java, src/test/resources/charges-delete-delta-source-1.json, src/test/resources/charges-delete-delta-source-2.json
added processing for delete charge functionality. Processor also calls delete endpoint on charge data api.
Added several unit tests for various classes
=> added delete endpoint and some unit tests for various classes

src/itest/resources/features/charges-consumer.feature, src/itest/resources/payloads/input/Notice_type_value_with_empty_space_Happy_Path.json, src/main/java/uk/gov/companieshouse/charges/delta/mapper/NoticeTypeTransDesc.java, src/main/java/uk/gov/companieshouse/charges/delta/mapper/TransactionsApiMapper.java, src/main/java/uk/gov/companieshouse/charges/delta/processor/EncoderUtil.java, src/main/java/uk/gov/companieshouse/charges/delta/transformer/ChargesApiTransformer.java, src/test/java/uk/gov/companieshouse/charges/delta/processor/EncoderUtilTest.java, src/test/java/uk/gov/companieshouse/charges/delta/transformer/ChargesApiTransformerTest.java, src/test/resources/charges-delta-source-12_notice_type_with_space_at_start.json
DSND-1005:fix E2E - CIDEV - charges - filing_type is made blank in the company_mortgage DB after the charges delta
=> DSND-1005:fix E2E - CIDEV - charges - filing_type is made blank in the company_mortgage DB after the charges delta

Makefile, pom.xml
Implementing Sonar Qube Changes
=> Implementing Sonar Qube Changes

src/itest/resources/features/charges-consumer.feature, src/itest/resources/payloads/input/charges-delta-source-3.json, src/itest/resources/payloads/output/internal-charges-api-expected-3.json, src/main/resources/noticeTypes.txt, src/test/java/uk/gov/companieshouse/charges/delta/transformer/ChargesApiTransformerTest.java, src/test/resources/charges-delta-source-18.json, src/test/resources/internal-charges-api-expected-18.json
DSND-1084:fix Staging-E2E-MG01 returns wrong filing type
=> DSND-1084:fix Staging-E2E-MG01 returns wrong filing type

src/main/java/uk/gov/companieshouse/charges/delta/mapper/ChargeApiMapper.java, src/main/java/uk/gov/companieshouse/charges/delta/processor/EncoderUtil.java
=> Improving code for Sonar Qube

src/main/java/uk/gov/companieshouse/charges/delta/processor/EncoderUtil.java
Excluding Sha1 code line for Sonar Qube
=> Excluding Sha1 code line for Sonar Qube

pom.xml, src/itest/resources/payloads/output/Insolvency_cases_Happy_Path_output.json, src/itest/resources/payloads/output/internal-charges-api-empty-dates-expected.json, src/itest/resources/payloads/output/internal-charges-api-expected-2.json, src/itest/resources/payloads/output/internal-charges-api-expected-3.json, src/test/resources/internal-charges-api-expected-2.json, src/test/resources/internal-charges-api-expected-empty-dates.json
DSND-1110 Update private-api-sdk-java.version in POM file and updated json files for testing
=> DSND-1110 Update private-api-sdk-java.version in POM file

pom.xml, src/main/java/uk/gov/companieshouse/charges/delta/mapper/DescriptiveChargeApiMapper.java, src/main/java/uk/gov/companieshouse/charges/delta/mapper/DescriptiveChargeApiMapperAspect.java, src/test/java/uk/gov/companieshouse/charges/delta/config/TestConfig.java, src/test/java/uk/gov/companieshouse/charges/delta/mapper/DescriptiveChargeApiMapperTest.java
* Remove feature toggle DESCRIPTIVE_MAPPINGS_ENABLED.
* Log mapped values in trace logs.
Resolves:
[DSND-1123](https://companieshouse.atlassian.net/browse/DSND-1123)
=> DSND-1123 Remove descriptive mapping feature toggle

src/itest/java/uk/gov/companieshouse/charges/delta/Hooks.java, src/itest/java/uk/gov/companieshouse/charges/delta/common/TestConstants.java, src/itest/java/uk/gov/companieshouse/charges/delta/config/DelegatingLatch.java, src/itest/java/uk/gov/companieshouse/charges/delta/config/KafkaTestContainerConfig.java, src/itest/java/uk/gov/companieshouse/charges/delta/consumer/ChargesDeltaConsumerAspect.java, src/itest/java/uk/gov/companieshouse/charges/delta/steps/ChargesConsumerDeleteSteps.java, src/itest/java/uk/gov/companieshouse/charges/delta/steps/ChargesConsumerErrorSteps.java, src/itest/java/uk/gov/companieshouse/charges/delta/steps/ChargesConsumerSteps.java, src/itest/resources/features/charges-delta-consumer-error-path.feature
* Fix race conditions in integration tests causing intermittent test
failures.
=> Fix intermittent build failures

src/main/java/uk/gov/companieshouse/charges/delta/mapper/TextFormatter.java, src/test/java/uk/gov/companieshouse/charges/delta/mapper/TextFormatterTest.java
* Substitute matching tokens in-place for better compatibility with
existing solution.
=> DSND-1135 Reimplement TextFormatter algorithms

src/main/java/uk/gov/companieshouse/charges/delta/mapper/TextFormatter.java, src/test/java/uk/gov/companieshouse/charges/delta/mapper/TextFormatterTest.java
* Convert any stop words delimited by a non-unicode letter into
lowercase (e.g. harrow-on-the-hill => Harrow-on-the-Hill).
Resolves:
[DSND-1135](https://companieshouse.atlassian.net/browse/DSND-1135)
=> DSND-1135 Convert stop words within a token to lowercase

src/main/java/uk/gov/companieshouse/charges/delta/mapper/TextFormatter.java, src/test/java/uk/gov/companieshouse/charges/delta/mapper/TextFormatterTest.java
* Words ending in multiple full stops not recognised as end-of-sentence.
=> DSND-1141 Fix issue with end-of-sentence pattern

src/main/java/uk/gov/companieshouse/charges/delta/mapper/TextFormatter.java, src/test/java/uk/gov/companieshouse/charges/delta/mapper/TextFormatterTest.java
* Remove newlines at very end of string before replacing with full stops
[DSND-1146](https://companieshouse.atlassian.net/browse/DSND-1146)
=> DSND-1146 Fix formatAsParticulars in TextFormatter

src/main/java/uk/gov/companieshouse/charges/delta/mapper/TextFormatter.java, src/test/java/uk/gov/companieshouse/charges/delta/mapper/TextFormatterTest.java
* Refactor previous code to use existing logic to sentence case first word
* Add new conditional check to above logic to handle casing inside brackets
Resolves [DSND-1161](https://companieshouse.atlassian.net/browse/DSND-1161)
=> DSND-1161 Fix bug where sentence casing isnt taking place inside brackets

src/test/resources/internal-charges-api-expected-19.json, src/test/resources/internal-charges-api-expected-20.json
This PR is to move the main transaction to the top of the transaction list for expected json files.
**Resolves**
- DSND-1127
=> Fix json files for unit tests

src/itest/resources/payloads/output/internal-charges-api-expected-19.json, src/itest/resources/payloads/output/internal-charges-api-expected-20.json
=> Fix json files for integration tests

src/main/java/uk/gov/companieshouse/charges/delta/mapper/TextFormatter.java, src/test/java/uk/gov/companieshouse/charges/delta/mapper/TextFormatterTest.java
* Fix possible vulnerability in end of sentence pattern in
TextFormatter.
Resolves:
[DSND-1170](https://companieshouse.atlassian.net/browse/DSND-1170)
=> DSND-1170 Fix vulnerability with end of sentence pattern

src/main/java/uk/gov/companieshouse/charges/delta/mapper/TextFormatter.java
* Fix build failures caused by checkstyles issues.
=> Fix checkstyle issues

src/itest/resources/features/charges-delta-consumer-error-path.feature, src/main/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessor.java
Amended to use NOT FOUND instead of GONE
BI-11641
=> Amended to use NOT FOUND instead of GONE

src/itest/resources/features/charges-delta-consumer-error-path.feature, src/main/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessor.java
Amendments to reverse changes made to replace GONE with NOT FOUND
BI-11641
=> Amendments to reverse changes made to replace GONE with NOT FOUND

src/itest/resources/features/charges-delta-consumer-error-path.feature, src/main/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessor.java, src/test/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessorTest.java
Changed HTTP GONE to HTTP NOT FOUND
BI-11789
=> Changed HTTP GONE to HTTP NOT FOUND

Makefile, pom.xml, src/itest/java/uk/gov/companieshouse/charges/delta/steps/ChargesConsumerDeleteSteps.java, src/itest/java/uk/gov/companieshouse/charges/delta/steps/ChargesConsumerErrorSteps.java, src/itest/resources/features/charges-delta-consumer-delete-flows.feature, src/itest/resources/payloads/input/charges-delete-delta-source-1.json, src/main/java/uk/gov/companieshouse/charges/delta/consumer/ChargesDeltaConsumer.java, src/main/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessor.java, src/main/java/uk/gov/companieshouse/charges/delta/service/ApiClientService.java, src/main/java/uk/gov/companieshouse/charges/delta/service/ApiClientServiceImpl.java, src/main/java/uk/gov/companieshouse/charges/delta/transformer/ChargesApiTransformer.java, src/test/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessorTest.java, src/test/java/uk/gov/companieshouse/charges/delta/service/ApiClientServiceImplTest.java, src/test/java/uk/gov/companieshouse/charges/delta/util/TestSupport.java, src/test/resources/charges-delete-delta-source-1.json
java 21 & springboot 3 upgrade changes
https://companieshouse.atlassian.net/browse/JU-907
=> Ju 907 java and spring upgrade

pom.xml
https://companieshouse.atlassian.net/browse/JU-907
=> updating jib-maven-plugin.version

pom.xml
https://companieshouse.atlassian.net/browse/JU-907
=> logging fix - removing logback exclusion in pom

pom.xml
https://companieshouse.atlassian.net/browse/ASM-506
Add latest Sonar config to Pom
=> ASM-506 Add latest Sonar config to Pom

pom.xml, src/main/java/uk/gov/companieshouse/charges/delta/transformer/ChargesApiTransformer.java
https://companieshouse.atlassian.net/browse/ASM-506
Use sonar plugin version from parent pom
Remove duplicate jib plugin causing warning in logs
=> ASM-506 sonar plugin update
